---
  - include: packages.yml
  - include: locale.yml
  - include: sudo.yml
  - include: molly-guard.yml
  - include: sshd.yml

  - include: user.yml user={{ users }}
    tags: user

  - name: adding message of the day
    template:
      dest: /etc/motd
      src: "{{ motd_path }}"
      owner: root
      group: root
      mode: 0644
    when: motd_path is defined
