---
- name: Update and upgrade apt packages
  apt:
    upgrade: "{{ base_upgrade }}"
    update_cache: yes
    cache_valid_time: 86400 # One day

- name: install a default set of packages
  package:
    name:
    - vim
    - nano
    - htop
    - git
    - tmux
    - screen
    - byobu
    - ncdu
    - moreutils
    - apt-transport-https
    - smartmontools
    - zip
    - unzip
    - zsh
    - rsync
    - gnupg
    - sudo
    - curl
    - python-pip
    - python3-pip
    - python-setuptools
    - python3-setuptools
    - python3-venv
    state: present
  tags: packages
